@echo off
echo Starting Trading Journal Application...

echo Starting Backend Server...
start cmd /k "cd backend && python app.py"

echo Starting Frontend Server...
start cmd /k "cd frontend && npm start"

echo Both servers are starting up...
echo Backend will be available at http://localhost:5000
echo Frontend will be available at http://localhost:3000 